### ISSUE TITLE
Odd looking navigation bar.

### ISSUE THREAD

**Issue by Tjoosten** [ScoutsGidsenVL/Pydio#4]
is it normal? Or looks the navigation odd? 
<img width="1280" alt="schermafbeelding 2016-05-13 om 01 51 04" src="https://cloud.githubusercontent.com/assets/5157609/15233977/41a5949a-18ad-11e6-90b8-f5e2f794e813.png">

**Comment by TinusVL** [comment]
It's a bit odd, but this is intended.
Do you have a better proposal?

**Comment by Tjoosten** [comment]
Hey Tinus, 

Ik denk dat heter beter uitziet als alles op 1 lijn staat. Maar echter weet ik niet dat dit mogelijk is. Plus het is maar een mening. Als je wilt sluit ik deze issue weer. 

Met vriendelijke groet, 
Tim Joosten
